#ifndef NEFORCE_CORE_CONFIG_VERSION_HPP__
#define NEFORCE_CORE_CONFIG_VERSION_HPP__

#ifdef NEFORCE_VERSION_MAJOR
#    undef NEFORCE_VERSION_MAJOR
#endif
#define NEFORCE_VERSION_MAJOR NEXUSFORCE_VERSION_MAJOR

#ifdef NEFORCE_VERSION_MINOR
#    undef NEFORCE_VERSION_MINOR
#endif
#define NEFORCE_VERSION_MINOR NEXUSFORCE_VERSION_MINOR

#ifdef NEFORCE_VERSION_PATCH
#    undef NEFORCE_VERSION_PATCH
#endif
#define NEFORCE_VERSION_PATCH NEXUSFORCE_VERSION_PATCH

#ifdef NEFORCE_VERSION
#    undef NEFORCE_VERSION
#endif
#define NEFORCE_VERSION NEXUSFORCE_VERSION

#endif // NEFORCE_CORE_CONFIG_VERSION_HPP__
