#ifndef NEFORCE_DATABASE_SQL_BUILDER_HPP__
#define NEFORCE_DATABASE_SQL_BUILDER_HPP__

/**
 * @file sql_builder.hpp
 * @brief SQL语句构建器
 *
 * 此文件提供了SQL语句的流式构建器。
 */

#include "NeForce/core/container/vector.hpp"
#include "NeForce/core/memory/unique_ptr.hpp"
#include "NeForce/core/string/string.hpp"
NEFORCE_BEGIN_NAMESPACE__

/**
 * @defgroup SQL SQL
 * @brief SQL语句的流式构建器实现
 *
 * 通过链式调用构建复杂的SQL语句，避免手动拼接SQL字符串的安全风险。
 *
 * **支持的语句类型：**
 * - DML: SELECT, INSERT, UPDATE, DELETE
 * - DDL: CREATE TABLE, ALTER TABLE, DROP TABLE, TRUNCATE TABLE
 * - 视图: CREATE VIEW, DROP VIEW
 * - 索引: CREATE INDEX, DROP INDEX
 * - 集合操作: UNION / UNION ALL / INTERSECT / INTERSECT ALL / EXCEPT / EXCEPT ALL
 * - CTE: WITH / WITH RECURSIVE
 * - 窗口函数: ROW_NUMBER, RANK, DENSE_RANK, NTILE, LEAD, LAG, FIRST_VALUE, LAST_VALUE
 * - 表达式工具: CASE, CAST
 * - 聚合: COUNT, SUM, AVG, MAX, MIN
 *
 * @section standards 遵循的SQL标准
 * 本构建器生成的语法遵循以下国际标准：
 * - **ISO/IEC 9075:1992** (SQL-92) Entry 级及 Intermediate 级核心语法
 *   https://www.iso.org/standard/16663.html
 * - **ISO/IEC 9075-2:1999** (SQL:1999/Foundation) CTE、派生表与子查询增强
 *   https://www.iso.org/standard/26196.html
 * - **ISO/IEC 9075-2:2003** (SQL:2003/Foundation) 窗口函数 (ROW_NUMBER / RANK / 等)
 * - **ISO/IEC 9075-2:2008** (SQL:2008/Foundation) TRUNCATE TABLE, FETCH FIRST 分页
 * - **ISO/IEC 9075-4:2023** (SQL/PSM) 预编译占位符相关约定
 *   https://www.iso.org/standard/76584.html
 *
 * 同时覆盖以下事实标准（跨数据库厂商通用，非 ANSI 标准正文）：
 * - CREATE INDEX / DROP INDEX
 * - CREATE [OR REPLACE] VIEW
 * - IF [NOT] EXISTS 修饰子句
 * - AUTO_INCREMENT 自增列 (MySQL/SQLite)
 * - LIMIT / OFFSET 分页 (MySQL/PostgreSQL/SQLite)
 *
 * @section compatibility 数据库兼容性
 * 生成的 SQL 语句适用于以下主流关系型数据库：
 * - MySQL 5.7+
 * - PostgreSQL 9.0+
 * - SQLite 3.0+
 * - Microsoft SQL Server 2008+
 * - Oracle Database 10g+
 * - 所有其他遵循 ANSI SQL 标准的数据库
 *
 * @note
 * - `LIMIT`/`OFFSET` 是事实标准，被除 Oracle 外的多数数据库支持。
 *   对 Oracle 12c+，建议使用 fetch_first() 生成 `FETCH FIRST n ROWS ONLY`。
 * - 构建器生成的 SQL 骨架使用 `?` 占位符；实际参数绑定与转义由驱动程序处理。
 *
 * @section exclusions 有意不纳入的特性及原因
 *
 * 以下 SQL 特性在标准中有定义但本构建器 **不提供 API 支持**。
 * 用户可通过传入原始 SQL 字符串（如 where()、having() 等）自由使用这些特性。
 *
 * | 特性 | 标准出处 | 不纳入原因 |
 * |------|---------|-----------|
 * | GRANT / REVOKE | SQL-92 Entry | DCL（数据控制语言），属于运维授权范畴，与 DML/DDL 性质不同 |
 * | CREATE SCHEMA / DOMAIN / ASSERTION | SQL-92 Intermediate | 生产代码中极少使用；多数数据库实现不完整或语义差异大 |
 * | TRIGGER / 存储过程 / 函数 | SQL:1999 / SQL/PSM | 过程式代码（含控制流），超出声明式 SQL 构建器的设计范围 |
 * | SAVEPOINT / RELEASE SAVEPOINT | SQL:1999 | 事务控制原语，粒度与连接层绑定；使用频率低 |
 * | MERGE (UPSERT) | SQL:2003 | 各数据库方言差异极大（MySQL ON DUPLICATE KEY / PostgreSQL ON CONFLICT / SQLite INSERT OR REPLACE），统一 API 会掩盖方言行为差异 |
 * | CREATE SEQUENCE / ALTER SEQUENCE | SQL:2003 | 多数项目通过 ORM 或迁移脚本管理序列，不适合运行时 SQL 构建器 |
 * | MATCH / OVERLAPS / UNIQUE 谓词 | SQL-92 Full | 边缘用例；多数数据库未实现或语义不完整，生产代码中几乎不会使用 |
 * | LATERAL JOIN | SQL:1999 | 使用率极低；可通过子查询或 CROSS JOIN 改写 |
 * | IDENTITY 列 (GENERATED AS IDENTITY) | SQL:2003 | 与 AUTO_INCREMENT 功能重叠；各数据库语法差异大 (GENERATED ALWAYS AS IDENTITY / GENERATED BY DEFAULT AS IDENTITY / IDENTITY(1,1)) |
 * | TEMPORARY TABLE (会话临时表) | SQL-92 Full | 本构建器已支持 CREATE TEMP TABLE (事实标准语法) |
 * @{
 */

#ifdef DELETE
#    undef DELETE
#endif

#ifdef EXCEPT
#    undef EXCEPT
#endif

#ifdef INTERSECT
#    undef INTERSECT
#endif

/**
 * @enum sql_operate
 * @brief SQL操作类型枚举
 */
enum class sql_operate : uint8_t {
    SELECT,       ///< SELECT查询
    INSERT,       ///< INSERT插入
    UPDATE,       ///< UPDATE更新
    DELETE,       ///< DELETE删除
    DROP_TABLE,   ///< DROP TABLE删除表
    CREATE_TABLE, ///< CREATE TABLE建表
    CREATE_VIEW,  ///< CREATE VIEW创建视图
    DROP_VIEW,    ///< DROP VIEW删除视图
    ALTER_TABLE,  ///< ALTER TABLE修改表
    CREATE_INDEX, ///< CREATE INDEX创建索引
    DROP_INDEX,   ///< DROP INDEX删除索引
    TRUNCATE      ///< TRUNCATE TABLE截断表
};

/**
 * @enum sql_join
 * @brief JOIN类型枚举
 */
enum class sql_join : uint8_t {
    INNER, ///< INNER JOIN
    LEFT,  ///< LEFT JOIN
    RIGHT, ///< RIGHT JOIN
    FULL   ///< FULL JOIN
};

/**
 * @enum sql_order
 * @brief 排序方向枚举
 */
enum class sql_order : uint8_t {
    ASC, ///< 升序
    DESC ///< 降序
};

/**
 * @enum sql_dialect
 * @brief 数据库方言
 *
 * 不同的数据库在语法和功能上存在差异，选择对应方言可生成最佳兼容的 SQL。
 */
enum class sql_dialect : uint8_t {
    GENERIC,    ///< ANSI SQL
    MYSQL,      ///< MySQL / MariaDB
    POSTGRESQL, ///< PostgreSQL
    SQLITE,     ///< SQLite
    MSSQL,      ///< Microsoft SQL Server
    ORACLE      ///< Oracle Database
};

/**
 * @enum sql_set_op
 * @brief 集合操作类型枚举
 */
enum class sql_set_op : uint8_t {
    UNION,         ///< UNION
    UNION_ALL,     ///< UNION ALL
    INTERSECT,     ///< INTERSECT
    INTERSECT_ALL, ///< INTERSECT ALL
    EXCEPT_,       ///< EXCEPT
    EXCEPT_ALL     ///< EXCEPT ALL
};


/**
 * @class sql_builder
 * @brief SQL语句构建器
 *
 * 提供流式API构建SQL语句：
 * - 支持SELECT、INSERT、UPDATE、DELETE操作
 * - 支持JOIN、WHERE、GROUP BY、ORDER BY、LIMIT等子句
 * - 支持聚合函数（COUNT、SUM、AVG、MAX、MIN）
 * - 支持子查询
 * - 自动处理SQL语法
 */
class NEFORCE_API sql_builder {
public:
    /**
     * @struct select_data
     * @brief SELECT语句的数据结构
     */
    struct select_data {
        vector<string> fields;            ///< 查询字段列表
        vector<string> join_clauses;      ///< JOIN子句列表
        vector<string> group_by_fields;   ///< GROUP BY字段列表
        vector<string> rollup_fields;     ///< GROUP BY ROLLUP字段列表
        vector<string> cube_fields;       ///< GROUP BY CUBE字段列表
        vector<string> having_conditions; ///< HAVING条件列表
        vector<string> order_by_clauses;  ///< ORDER BY子句列表
        int limit_count = -1;             ///< LIMIT数量
        int offset_count = -1;            ///< OFFSET数量
        int fetch_count = -1;             ///< FETCH FIRST 行数（SQL:2008分页）
        bool distinct = false;            ///< 是否DISTINCT
    };

    /**
     * @struct insert_data
     * @brief INSERT语句的数据结构
     */
    struct insert_data {
        vector<string> fields;             ///< 插入字段列表
        vector<string> placeholders;       ///< 第一行值占位符列表
        vector<vector<string>> extra_rows; ///< 额外的多行VALUES（用于批量插入）
    };

    /**
     * @struct update_data
     * @brief UPDATE语句的数据结构
     */
    struct update_data {
        vector<string> assignments; ///< 赋值表达式列表
    };

    /**
     * @struct column_definition
     * @brief 列定义
     */
    struct column_definition {
        string name;                 ///< 列名
        string type;                 ///< 列类型
        bool not_null = false;       ///< NOT NULL约束
        bool unique_ = false;        ///< UNIQUE约束
        bool primary_key = false;    ///< PRIMARY KEY约束
        bool auto_increment = false; ///< AUTO_INCREMENT（事实标准）
        string default_value;        ///< DEFAULT值
        string check_expr;           ///< CHECK表达式
    };

    /**
     * @struct create_table_data
     * @brief CREATE TABLE语句的数据结构
     */
    struct create_table_data {
        vector<column_definition> columns; ///< 列定义列表
        vector<string> table_constraints;  ///< 表级约束（预组装的SQL子句）
        bool if_not_exists = false;        ///< 是否使用IF NOT EXISTS
        bool temporary = false;            ///< 是否创建临时表（TEMP TABLE）
    };

    /**
     * @struct create_view_data
     * @brief CREATE VIEW语句的数据结构
     */
    struct create_view_data {
        string view_name;        ///< 视图名
        string view_query;       ///< 视图查询SQL
        bool or_replace = false; ///< 是否使用OR REPLACE
    };

    /**
     * @struct alter_table_data
     * @brief ALTER TABLE语句的数据结构
     */
    struct alter_table_data {
        vector<string> actions; ///< 预组装的ALTER操作子句
    };

    /**
     * @struct create_index_data
     * @brief CREATE INDEX语句的数据结构
     */
    struct create_index_data {
        string index_name;      ///< 索引名
        string table_name;      ///< 表名
        vector<string> columns; ///< 列列表
        bool unique = false;    ///< 是否UNIQUE索引
    };

    /**
     * @struct set_op_entry
     * @brief 集合操作条目
     */
    struct set_op_entry {
        sql_set_op op; ///< 集合操作类型
        string query;  ///< 子查询SQL
    };

    /**
     * @struct cte_entry
     * @brief CTE条目
     */
    struct cte_entry {
        string name;            ///< CTE名称
        string query;           ///< CTE查询SQL
        bool recursive = false; ///< 是否递归CTE
    };

private:
    sql_operate sql_type_ = sql_operate::SELECT; ///< 当前SQL操作类型
    sql_dialect dialect_ = sql_dialect::GENERIC; ///< 目标数据库方言
    size_t param_seq_ = 0;                       ///< 参数序号计数器
    string table_;                               ///< 主表名
    string table_alias_;                         ///< 主表别名
    vector<string> where_conditions_;            ///< WHERE条件列表
    vector<set_op_entry> set_operations_;        ///< 集合操作列表
    vector<cte_entry> cte_entries_;              ///< CTE条目列表
    bool drop_if_exists_ = false;                ///< DROP TABLE时是否使用IF EXISTS

    unique_ptr<select_data> select_data_;             ///< SELECT专用数据
    unique_ptr<insert_data> insert_data_;             ///< INSERT专用数据
    unique_ptr<update_data> update_data_;             ///< UPDATE专用数据
    unique_ptr<create_table_data> create_table_data_; ///< CREATE TABLE专用数据
    unique_ptr<create_view_data> create_view_data_;   ///< CREATE VIEW专用数据
    unique_ptr<alter_table_data> alter_table_data_;   ///< ALTER TABLE专用数据
    unique_ptr<create_index_data> create_index_data_; ///< CREATE INDEX专用数据

private:
    select_data* ensure_select_data();
    insert_data* ensure_insert_data();
    update_data* ensure_update_data();
    create_table_data* ensure_create_table_data();
    create_view_data* ensure_create_view_data();
    alter_table_data* ensure_alter_table_data();
    create_index_data* ensure_create_index_data();

    void clear_data() noexcept;

    NEFORCE_NODISCARD string make_placeholder(size_t index) const;

public:
    /**
     * @brief 默认构造函数
     */
    sql_builder() = default;

    /**
     * @brief 析构函数
     */
    ~sql_builder() = default;

    /**
     * @brief 拷贝构造函数
     * @param other 源对象
     */
    sql_builder(const sql_builder& other);

    /**
     * @brief 拷贝赋值运算符
     * @param other 源对象
     * @return 自身引用
     */
    sql_builder& operator=(const sql_builder& other);

    /**
     * @brief 移动构造函数
     * @param other 源对象
     */
    sql_builder(sql_builder&& other) noexcept = default;

    /**
     * @brief 移动赋值运算符
     * @param other 源对象
     * @return 自身引用
     */
    sql_builder& operator=(sql_builder&& other) noexcept = default;

    /**
     * @brief 列表设置SELECT字段
     * @param fields 字段列表
     * @return 自身引用
     */
    sql_builder& select(vector<string> fields);

    /**
     * @brief 初始化列表设置SELECT字段
     * @param fields 字段列表
     * @return 自身引用
     */
    sql_builder& select(std::initializer_list<string> fields);

    /**
     * @brief 添加SELECT字段
     * @param field 字段名
     * @return 自身引用
     */
    sql_builder& select(string field);

    /**
     * @brief 选择所有字段（SELECT *）
     * @return 自身引用
     */
    sql_builder& select_all() noexcept;

    /**
     * @brief 添加DISTINCT关键字
     * @return 自身引用
     */
    sql_builder& distinct();

    /**
     * @brief 设置主表
     * @param table 表名
     * @return 自身引用
     */
    sql_builder& from(string table) noexcept;

    /**
     * @brief 设置主表并指定别名
     * @param table 表名
     * @param alias 表别名
     * @return 自身引用
     */
    sql_builder& from(string table, string alias) noexcept;

    /**
     * @brief 添加JOIN子句
     * @param type JOIN类型
     * @param table 连接表名
     * @param on_condition ON条件
     * @return 自身引用
     */
    sql_builder& join(sql_join type, string table, string on_condition);

    /**
     * @brief 添加INNER JOIN子句
     * @param table 连接表名
     * @param on_condition ON条件
     * @return 自身引用
     */
    sql_builder& join(string table, string on_condition);

    /**
     * @brief 添加LEFT JOIN子句
     * @param table 连接表名
     * @param on_condition ON条件
     * @return 自身引用
     */
    sql_builder& left_join(string table, string on_condition);

    /**
     * @brief 添加RIGHT JOIN子句
     * @param table 连接表名
     * @param on_condition ON条件
     * @return 自身引用
     */
    sql_builder& right_join(string table, string on_condition);

    /**
     * @brief 添加INNER JOIN子句
     * @param table 连接表名
     * @param on_condition ON条件
     * @return 自身引用
     */
    sql_builder& inner_join(string table, string on_condition);

    /**
     * @brief 添加FULL JOIN子句
     * @param table 连接表名
     * @param on_condition ON条件
     * @return 自身引用
     */
    sql_builder& full_join(string table, string on_condition);

    /**
     * @brief 添加WHERE条件
     * @param condition 条件表达式
     * @return 自身引用
     */
    sql_builder& where(string condition);

    /**
     * @brief 添加相等条件
     * @param field 字段名
     * @param value 值
     * @return 自身引用
     */
    sql_builder& where_eq(string field, string value);

    /**
     * @brief 添加不等条件
     * @param field 字段名
     * @param value 值
     * @return 自身引用
     */
    sql_builder& where_ne(string field, string value);

    /**
     * @brief 添加大于条件
     * @param field 字段名
     * @param value 值
     * @return 自身引用
     */
    sql_builder& where_gt(string field, string value);

    /**
     * @brief 添加大于等于条件
     * @param field 字段名
     * @param value 值
     * @return 自身引用
     */
    sql_builder& where_ge(string field, string value);

    /**
     * @brief 添加小于条件
     * @param field 字段名
     * @param value 值
     * @return 自身引用
     */
    sql_builder& where_lt(string field, string value);

    /**
     * @brief 添加小于等于条件
     * @param field 字段名
     * @param value 值
     * @return 自身引用
     */
    sql_builder& where_le(string field, string value);

    /**
     * @brief 添加LIKE条件
     * @param field 字段名
     * @param pattern 模式
     * @return 自身引用
     */
    sql_builder& where_like(string field, string pattern);

    /**
     * @brief 添加NOT LIKE条件
     * @param field 字段名
     * @param pattern 模式
     * @return 自身引用
     */
    sql_builder& where_not_like(string field, string pattern);

    /**
     * @brief 添加IN条件
     * @param field 字段名
     * @param values 值列表
     * @return 自身引用
     */
    sql_builder& where_in(string field, vector<string> values);

    /**
     * @brief 添加NOT IN条件
     * @param field 字段名
     * @param values 值列表
     * @return 自身引用
     */
    sql_builder& where_not_in(string field, vector<string> values);

    /**
     * @brief 添加BETWEEN条件
     * @param field 字段名
     * @param start 起始值
     * @param end 结束值
     * @return 自身引用
     */
    sql_builder& where_between(string field, string start, string end);

    /**
     * @brief 添加NOT BETWEEN条件
     * @param field 字段名
     * @param start 起始值
     * @param end 结束值
     * @return 自身引用
     */
    sql_builder& where_not_between(string field, string start, string end);

    /**
     * @brief 添加IS NULL条件
     * @param field 字段名
     * @return 自身引用
     */
    sql_builder& where_is_null(string field);

    /**
     * @brief 添加IS NOT NULL条件
     * @param field 字段名
     * @return 自身引用
     */
    sql_builder& where_is_not_null(string field);

    /**
     * @brief 添加EXISTS条件
     * @param subquery 子查询
     * @return 自身引用
     */
    sql_builder& where_exists(string subquery);

    /**
     * @brief 添加NOT EXISTS条件
     * @param subquery 子查询
     * @return 自身引用
     */
    sql_builder& where_not_exists(string subquery);

    /**
     * @brief 添加OR条件（与上一个条件组合）
     * @param condition 条件表达式
     * @return 自身引用
     *
     * 将当前条件与上一个条件用OR连接。
     */
    sql_builder& or_where(string condition);

    /**
     * @brief 添加GROUP BY字段
     * @param field 字段名
     * @return 自身引用
     */
    sql_builder& group_by(string field);

    /**
     * @brief 添加GROUP BY字段列表
     * @param fields 字段列表
     * @return 自身引用
     */
    sql_builder& group_by(const vector<string>& fields);

    /**
     * @brief 添加GROUP BY ROLLUP子句
     * @param fields ROLLUP字段列表
     * @return 自身引用
     *
     * 生成 GROUP BY ROLLUP(field1, field2, ...) 语法，
     * 在每一层级产生小计行。
     */
    sql_builder& group_by_rollup(vector<string> fields);

    /**
     * @brief 添加GROUP BY CUBE子句
     * @param fields CUBE字段列表
     * @return 自身引用
     *
     * 生成 GROUP BY CUBE(field1, field2, ...) 语法，
     * 产生所有维度组合的小计行。
     */
    sql_builder& group_by_cube(vector<string> fields);

    /**
     * @brief 添加HAVING条件
     * @param condition 条件表达式
     * @return 自身引用
     */
    sql_builder& having(string condition);

    /**
     * @brief 添加ORDER BY子句
     * @param field 字段名
     * @param order 排序方向
     * @return 自身引用
     */
    sql_builder& order_by(string field, sql_order order = sql_order::ASC);

    /**
     * @brief 添加升序排序
     * @param field 字段名
     * @return 自身引用
     */
    sql_builder& order_by_asc(string field);

    /**
     * @brief 添加降序排序
     * @param field 字段名
     * @return 自身引用
     */
    sql_builder& order_by_desc(string field);

    /**
     * @brief 添加LIMIT限制
     * @param count 返回行数
     * @return 自身引用
     */
    sql_builder& limit(int count);

    /**
     * @brief 添加OFFSET偏移
     * @param count 偏移行数
     * @return 自身引用
     */
    sql_builder& offset(int count);

    /**
     * @brief 添加FETCH FIRST分页
     * @param row_count 返回行数
     * @return 自身引用
     *
     * 生成 FETCH FIRST n ROWS ONLY 语法，是 ANSI SQL:2008 标准分页方式。
     * 调用此方法后，LIMIT 子句将被忽略（以 FETCH FIRST 为准）。
     * 可与 offset() 组合生成 OFFSET m ROWS FETCH FIRST n ROWS ONLY。
     */
    sql_builder& fetch_first(int row_count);

    /**
     * @brief 添加分页
     * @param page_num 页码（从1开始）
     * @param page_size 每页大小
     * @return 自身引用
     */
    sql_builder& page(int page_num, int page_size);

    /**
     * @brief 设置INSERT INTO表名和字段
     * @param table 表名
     * @param fields 字段列表
     * @return 自身引用
     */
    sql_builder& insert_into(string table, vector<string> fields);

    /**
     * @brief 设置INSERT INTO表名
     * @param table 表名
     * @return 自身引用
     */
    sql_builder& insert_into(string table);

    /**
     * @brief 设置VALUES占位符
     * @param values 值占位符列表（如"?"或实际值）
     * @return 自身引用
     */
    sql_builder& values(vector<string> values);

    /**
     * @brief 设置VALUES占位符
     * @param values 值占位符初始化列表（如"?"或实际值）
     * @return 自身引用
     */
    sql_builder& values(std::initializer_list<string> values);

    /**
     * @brief 设置多行VALUES（批量插入）
     * @param value_rows 值占位符列表的列表，第一行为主行，其余为附加行
     * @return 自身引用
     */
    sql_builder& values(vector<vector<string>> value_rows);

    /**
     * @brief 追加一行VALUES（用于多行INSERT）
     * @param values 值占位符列表
     * @return 自身引用
     */
    sql_builder& add_values(vector<string> values);

    /**
     * @brief 设置INSERT字段列表
     * @param fields 字段列表
     * @return 自身引用
     */
    sql_builder& columns(vector<string> fields);

    /**
     * @brief 设置UPDATE表名
     * @param table 表名
     * @return 自身引用
     */
    sql_builder& update(string table);

    /**
     * @brief 添加SET赋值
     * @param assignment 赋值表达式（如"field = value"）
     * @return 自身引用
     */
    sql_builder& set(string assignment);

    /**
     * @brief 添加SET赋值（字段=值形式）
     * @param field 字段名
     * @param value 值
     * @return 自身引用
     */
    sql_builder& set(string field, string value);

    /**
     * @brief 添加自增赋值
     * @param field 字段名
     * @param value 增加量，默认为1
     * @return 自身引用
     */
    sql_builder& set_increment(string field, int value = 1);

    /**
     * @brief 添加自减赋值
     * @param field 字段名
     * @param value 减少量，默认为1
     * @return 自身引用
     */
    sql_builder& set_decrement(string field, int value = 1);

    /**
     * @brief 设置DELETE操作
     * @return 自身引用
     */
    sql_builder& remove();

    /**
     * @brief 设置DELETE FROM表名
     * @param table 表名
     * @return 自身引用
     */
    sql_builder& delete_from(string table);

    /**
     * @brief 删除表
     * @param table 表名
     * @return 自身引用
     */
    sql_builder& drop_table(string table);

    /**
     * @brief 删除表（IF EXISTS）
     * @param table 表名
     * @return 自身引用
     */
    sql_builder& drop_table_if_exists(string table);

    /**
     * @brief 添加UNION集合操作
     * @param query 要合并的查询SQL
     * @return 自身引用
     */
    sql_builder& union_(string query);

    /**
     * @brief 添加UNION ALL集合操作
     * @param query 要合并的查询SQL
     * @return 自身引用
     */
    sql_builder& union_all(string query);

    /**
     * @brief 添加INTERSECT集合操作
     * @param query 要合并的查询SQL
     * @return 自身引用
     */
    sql_builder& intersect(string query);

    /**
     * @brief 添加INTERSECT ALL集合操作
     * @param query 要合并的查询SQL
     * @return 自身引用
     */
    sql_builder& intersect_all(string query);

    /**
     * @brief 添加EXCEPT集合操作
     * @param query 要排除的查询SQL
     * @return 自身引用
     */
    sql_builder& except_(string query);

    /**
     * @brief 添加EXCEPT ALL集合操作
     * @param query 要排除的查询SQL
     * @return 自身引用
     */
    sql_builder& except_all(string query);

    /**
     * @brief 添加CTE（WITH子句）
     * @param name CTE名称
     * @param query CTE查询SQL
     * @return 自身引用
     */
    sql_builder& with_(string name, string query);

    /**
     * @brief 添加递归CTE（WITH RECURSIVE子句）
     * @param name CTE名称
     * @param query CTE查询SQL
     * @return 自身引用
     */
    sql_builder& with_recursive(string name, string query);

    /**
     * @brief 添加CROSS JOIN子句
     * @param table 表名
     * @return 自身引用
     */
    sql_builder& cross_join(string table);

    /**
     * @brief 添加ROW_NUMBER窗口函数
     * @param alias 结果别名
     * @param partition_by PARTITION BY字段列表（可选）
     * @param order_by ORDER BY字段列表（可选）
     * @return 自身引用
     */
    sql_builder& select_row_number(string alias, const vector<string>& partition_by = {},
                                   const vector<string>& order_by = {});

    /**
     * @brief 添加RANK窗口函数
     * @param alias 结果别名
     * @param partition_by PARTITION BY字段列表（可选）
     * @param order_by ORDER BY字段列表（可选）
     * @return 自身引用
     */
    sql_builder& select_rank(string alias, const vector<string>& partition_by = {},
                             const vector<string>& order_by = {});

    /**
     * @brief 添加DENSE_RANK窗口函数
     * @param alias 结果别名
     * @param partition_by PARTITION BY字段列表（可选）
     * @param order_by ORDER BY字段列表（可选）
     * @return 自身引用
     */
    sql_builder& select_dense_rank(string alias, const vector<string>& partition_by = {},
                                   const vector<string>& order_by = {});

    /**
     * @brief 添加NTILE窗口函数
     * @param buckets 分桶数量
     * @param alias 结果别名
     * @param partition_by PARTITION BY字段列表（可选）
     * @param order_by ORDER BY字段列表（可选）
     * @return 自身引用
     */
    sql_builder& select_ntile(int buckets, string alias, const vector<string>& partition_by = {},
                              const vector<string>& order_by = {});

    /**
     * @brief 添加LEAD窗口函数
     * @param field 目标字段名
     * @param alias 结果别名
     * @param partition_by PARTITION BY字段列表（可选）
     * @param order_by ORDER BY字段列表（可选）
     * @return 自身引用
     */
    sql_builder& select_lead(string field, string alias, const vector<string>& partition_by = {},
                             const vector<string>& order_by = {});

    /**
     * @brief 添加LAG窗口函数
     * @param field 目标字段名
     * @param alias 结果别名
     * @param partition_by PARTITION BY字段列表（可选）
     * @param order_by ORDER BY字段列表（可选）
     * @return 自身引用
     */
    sql_builder& select_lag(string field, string alias, const vector<string>& partition_by = {},
                            const vector<string>& order_by = {});

    /**
     * @brief 添加FIRST_VALUE窗口函数
     * @param field 目标字段名
     * @param alias 结果别名
     * @param partition_by PARTITION BY字段列表（可选）
     * @param order_by ORDER BY字段列表（可选）
     * @return 自身引用
     */
    sql_builder& select_first_value(string field, string alias, const vector<string>& partition_by = {},
                                    const vector<string>& order_by = {});

    /**
     * @brief 添加LAST_VALUE窗口函数
     * @param field 目标字段名
     * @param alias 结果别名
     * @param partition_by PARTITION BY字段列表（可选）
     * @param order_by ORDER BY字段列表（可选）
     * @return 自身引用
     */
    sql_builder& select_last_value(string field, string alias, const vector<string>& partition_by = {},
                                   const vector<string>& order_by = {});

    /**
     * @brief 构建简单CASE表达式（CASE field WHEN ... THEN ... ELSE ... END）
     * @param field CASE目标字段
     * @param when_then WHEN-THEN对列表
     * @param else_val ELSE默认值（可选，为空则省略ELSE子句）
     * @return 完整的CASE表达式字符串
     */
    static string make_case_simple(string field, vector<pair<string, string>> when_then, string else_val = "");

    /**
     * @brief 构建搜索CASE表达式（CASE WHEN condition THEN ... ELSE ... END）
     * @param when_then WHEN-THEN对列表，每对包含条件和结果
     * @param else_val ELSE默认值（可选，为空则省略ELSE子句）
     * @return 完整的CASE表达式字符串
     */
    static string make_case_searched(vector<pair<string, string>> when_then, string else_val = "");

    /**
     * @brief 构建CAST类型转换表达式
     * @param expression 源表达式
     * @param target_type 目标类型
     * @return CAST(expression AS target_type) 字符串
     */
    static string make_cast(string expression, string target_type);

    /**
     * @brief 创建表
     * @param table 表名
     * @return 自身引用
     */
    sql_builder& create_table(string table);

    /**
     * @brief 创建表（IF NOT EXISTS）
     * @param table 表名
     * @return 自身引用
     */
    sql_builder& create_table_if_not_exists(string table);

    /**
     * @brief 创建临时表（TEMP TABLE）
     * @param table 表名
     * @return 自身引用
     */
    sql_builder& create_temp_table(string table);

    /**
     * @brief 创建临时表（TEMP TABLE IF NOT EXISTS）
     * @param table 表名
     * @return 自身引用
     */
    sql_builder& create_temp_table_if_not_exists(string table);

    /**
     * @brief 添加基础列定义
     * @param name 列名
     * @param type 数据类型
     * @return 自身引用
     */
    sql_builder& column(string name, string type);

    /**
     * @brief 添加带NOT NULL约束的列定义
     * @param name 列名
     * @param type 数据类型
     * @return 自身引用
     */
    sql_builder& column_not_null(string name, string type);

    /**
     * @brief 添加PRIMARY KEY列定义
     * @param name 列名
     * @param type 数据类型
     * @return 自身引用
     */
    sql_builder& column_primary_key(string name, string type);

    /**
     * @brief 添加带UNIQUE约束的列定义
     * @param name 列名
     * @param type 数据类型
     * @return 自身引用
     */
    sql_builder& column_unique(string name, string type);

    /**
     * @brief 添加带DEFAULT值的列定义
     * @param name 列名
     * @param type 数据类型
     * @param default_val 默认值（需自行包含引号等）
     * @return 自身引用
     */
    sql_builder& column_default(string name, string type, string default_val);

    /**
     * @brief 添加带CHECK约束的列定义
     * @param name 列名
     * @param type 数据类型
     * @param check_expr CHECK表达式
     * @return 自身引用
     */
    sql_builder& column_check(string name, string type, string check_expr);

    /**
     * @brief 添加自增主键列定义（事实标准：AUTO_INCREMENT）
     * @param name 列名
     * @param type 数据类型
     * @return 自身引用
     */
    sql_builder& column_auto_increment(string name, string type);

    /**
     * @brief 添加表级PRIMARY KEY约束
     * @param columns 主键列列表
     * @return 自身引用
     */
    sql_builder& table_primary_key(vector<string> columns);

    /**
     * @brief 添加表级FOREIGN KEY约束
     * @param column 外键列名
     * @param ref_table 引用表名
     * @param ref_column 引用列名
     * @return 自身引用
     */
    sql_builder& table_foreign_key(string column, string ref_table, string ref_column);

    /**
     * @brief 添加表级UNIQUE约束
     * @param columns 唯一约束列列表
     * @return 自身引用
     */
    sql_builder& table_unique(vector<string> columns);

    /**
     * @brief 添加表级CHECK约束
     * @param expr CHECK表达式
     * @return 自身引用
     */
    sql_builder& table_check(string expr);

    /**
     * @brief 修改表
     * @param table 表名
     * @return 自身引用
     */
    sql_builder& alter_table(string table);

    /**
     * @brief 添加列（ALTER TABLE ADD COLUMN）
     * @param name 列名
     * @param type 数据类型
     * @return 自身引用
     */
    sql_builder& add_column(string name, string type);

    /**
     * @brief 删除列（ALTER TABLE DROP COLUMN）
     * @param name 列名
     * @return 自身引用
     */
    sql_builder& drop_column(string name);

    /**
     * @brief 修改列数据类型（ALTER TABLE ALTER COLUMN SET DATA TYPE）
     * @param name 列名
     * @param new_type 新数据类型
     * @return 自身引用
     */
    sql_builder& alter_column_set_type(string name, string new_type);

    /**
     * @brief 设置列默认值（ALTER TABLE ALTER COLUMN SET DEFAULT）
     * @param name 列名
     * @param default_val 默认值（需自行包含引号等）
     * @return 自身引用
     */
    sql_builder& alter_column_set_default(string name, string default_val);

    /**
     * @brief 删除列默认值（ALTER TABLE ALTER COLUMN DROP DEFAULT）
     * @param name 列名
     * @return 自身引用
     */
    sql_builder& alter_column_drop_default(string name);

    /**
     * @brief 设置列非空约束（ALTER TABLE ALTER COLUMN SET NOT NULL）
     * @param name 列名
     * @return 自身引用
     */
    sql_builder& alter_column_set_not_null(string name);

    /**
     * @brief 删除列非空约束（ALTER TABLE ALTER COLUMN DROP NOT NULL）
     * @param name 列名
     * @return 自身引用
     */
    sql_builder& alter_column_drop_not_null(string name);

    /**
     * @brief 重命名列（ALTER TABLE RENAME COLUMN）
     * @param old_name 旧列名
     * @param new_name 新列名
     * @return 自身引用
     */
    sql_builder& rename_column(string old_name, string new_name);

    /**
     * @brief 添加主键约束（ALTER TABLE ADD PRIMARY KEY）
     * @param columns 主键列列表
     * @return 自身引用
     */
    sql_builder& add_primary_key(vector<string> columns);

    /**
     * @brief 删除约束（ALTER TABLE DROP CONSTRAINT）
     * @param constraint_name 约束名称
     * @return 自身引用
     */
    sql_builder& drop_constraint(string constraint_name);

    /**
     * @brief 创建视图
     * @param view_name 视图名
     * @param select_query 视图查询SQL
     * @return 自身引用
     */
    sql_builder& create_view(string view_name, string select_query);

    /**
     * @brief 创建视图（OR REPLACE）
     * @param view_name 视图名
     * @param select_query 视图查询SQL
     * @return 自身引用
     */
    sql_builder& create_or_replace_view(string view_name, string select_query);

    /**
     * @brief 删除视图
     * @param view_name 视图名
     * @return 自身引用
     */
    sql_builder& drop_view(string view_name);

    /**
     * @brief 删除视图（IF EXISTS）
     * @param view_name 视图名
     * @return 自身引用
     */
    sql_builder& drop_view_if_exists(string view_name);

    /**
     * @brief 创建索引（CREATE INDEX）
     * @param index_name 索引名
     * @param table 表名
     * @param columns 索引列列表
     * @return 自身引用
     */
    sql_builder& create_index(string index_name, string table, vector<string> columns);

    /**
     * @brief 创建唯一索引（CREATE UNIQUE INDEX）
     * @param index_name 索引名
     * @param table 表名
     * @param columns 索引列列表
     * @return 自身引用
     */
    sql_builder& create_unique_index(string index_name, string table, vector<string> columns);

    /**
     * @brief 删除索引（DROP INDEX）
     * @param index_name 索引名
     * @return 自身引用
     */
    sql_builder& drop_index(string index_name);

    /**
     * @brief 删除索引（DROP INDEX IF EXISTS）
     * @param index_name 索引名
     * @return 自身引用
     */
    sql_builder& drop_index_if_exists(string index_name);

    /**
     * @brief 截断表（TRUNCATE TABLE）
     * @param table 表名
     * @return 自身引用
     */
    sql_builder& truncate(string table);

    /**
     * @brief 添加COUNT聚合函数（带别名）
     * @param field 计数字段名
     * @param alias 结果别名
     * @return 自身引用
     */
    sql_builder& select_count(string field, string alias);

    /**
     * @brief 添加COUNT聚合函数（无别名）
     * @param field 计数字段名
     * @return 自身引用
     */
    sql_builder& select_count(string field);

    /**
     * @brief 添加COUNT(*)聚合函数
     * @return 自身引用
     */
    sql_builder& select_count();

    /**
     * @brief 添加SUM聚合函数（带别名）
     * @param field 求和字段名
     * @param alias 结果别名
     * @return 自身引用
     */
    sql_builder& select_sum(string field, string alias);

    /**
     * @brief 添加SUM聚合函数（无别名）
     * @param field 求和字段名
     * @return 自身引用
     */
    sql_builder& select_sum(string field);

    /**
     * @brief 添加AVG聚合函数（带别名）
     * @param field 求平均字段名
     * @param alias 结果别名
     * @return 自身引用
     */
    sql_builder& select_avg(string field, string alias);

    /**
     * @brief 添加AVG聚合函数（无别名）
     * @param field 求平均字段名
     * @return 自身引用
     */
    sql_builder& select_avg(string field);

    /**
     * @brief 添加MAX聚合函数（带别名）
     * @param field 求最大字段名
     * @param alias 结果别名
     * @return 自身引用
     */
    sql_builder& select_max(string field, string alias);

    /**
     * @brief 添加MAX聚合函数（无别名）
     * @param field 求最大字段名
     * @return 自身引用
     */
    sql_builder& select_max(string field);

    /**
     * @brief 添加MIN聚合函数（带别名）
     * @param field 求最小字段名
     * @param alias 结果别名
     * @return 自身引用
     */
    sql_builder& select_min(string field, string alias);

    /**
     * @brief 添加MIN聚合函数（无别名）
     * @param field 求最小字段名
     * @return 自身引用
     */
    sql_builder& select_min(string field);

    /**
     * @brief 添加DISTINCT字段
     * @param field 字段名
     * @return 自身引用
     */
    sql_builder& select_distinct(string field);

    /**
     * @brief 添加子查询作为SELECT字段
     * @param subquery 子查询SQL
     * @param alias 别名
     * @return 自身引用
     */
    sql_builder& select_subquery(string subquery, string alias);

    /**
     * @brief 添加子查询作为SELECT字段（无别名）
     * @param subquery 子查询SQL
     * @return 自身引用
     */
    sql_builder& select_subquery(string subquery);

    /**
     * @brief 使用子查询作为FROM表
     * @param subquery 子查询SQL
     * @param alias 别名
     * @return 自身引用
     */
    sql_builder& from_subquery(string subquery, string alias);

    /**
     * @brief 重置构建器状态
     * @return 自身引用
     */
    sql_builder& reset() noexcept;

    /**
     * @brief 获取当前SQL操作类型
     * @return 操作类型
     */
    NEFORCE_NODISCARD sql_operate type() const noexcept { return sql_type_; }

    /**
     * @brief 获取当前表名
     * @return 表名视图
     */
    NEFORCE_NODISCARD string_view table() const noexcept { return table_.view(); }

    /**
     * @brief 检查构建器是否为空
     * @return 未设置表名返回true
     */
    NEFORCE_NODISCARD bool is_empty() const noexcept { return table_.empty(); }

    /**
     * @brief 设置数据库方言
     * @param dialect 目标数据库方言
     * @return 自身引用
     *
     * 设置后 build() 会根据方言调整生成的 SQL 语法。
     */
    sql_builder& set_dialect(const sql_dialect dialect) noexcept {
        dialect_ = dialect;
        return *this;
    }

    /**
     * @brief 获取当前数据库方言
     * @return 方言枚举值
     */
    NEFORCE_NODISCARD sql_dialect dialect() const noexcept { return dialect_; }

    /**
     * @brief 获取当前语句的参数占位符数量
     * @return 参数总数（方言无关）
     *
     * 数量由内部计数器追踪，与占位符格式（`?` / `$N` / `:N`）无关。
     * - 通过 insert_into() / columns() 自动填充时同步
     * - 通过 set_param() / next_placeholder() 时自增
     */
    NEFORCE_NODISCARD size_t param_count() const noexcept { return param_seq_; }

    /**
     * @brief 生成方言感知的参数占位符
     * @param index 参数序号（1-based）
     * @return 占位符字符串
     * @note 仅当手动调用 values() / add_values() / set() 时才需自行调用
     */
    NEFORCE_NODISCARD string placeholder(const size_t index) const { return make_placeholder(index); }

    /**
     * @brief 获取下一个参数占位符
     * @return 占位符字符串
     *
     * 每次调用后内部序号 +1，用于 UPDATE/SELECT 中按顺序分配占位符
     *
     * @note 调用 reset() 时序号归零
     */
    NEFORCE_NODISCARD string next_placeholder() { return make_placeholder(++param_seq_); }

    /**
     * @brief 添加 SET 赋值
     * @param field 字段名
     * @return 自身引用
     *
     * 自动使用下一个参数占位符
     */
    sql_builder& set_param(string field) { return set(move(field), next_placeholder()); }

    /**
     * @brief 构建最终的SQL语句
     * @return 完整的SQL字符串
     * @throws value_exception 当SQL结构不完整时抛出
     *
     * 根据当前构建的状态生成完整的SQL语句。
     */
    NEFORCE_NODISCARD string build() const;
};

/** @} */ // SQL

NEFORCE_END_NAMESPACE__
#endif // NEFORCE_DATABASE_SQL_BUILDER_HPP__
