#ifndef MSTL_MSTL_HPP__
#define MSTL_MSTL_HPP__

/**
 * @file MSTL.hpp
 * @brief MSTL常用功能集
 *
 * 此文件提供了所有常用功能的头文件集合。
 */

#include "MSTL/compress/zlib_compress.hpp"
#include "MSTL/core/algorithm/algorithm.hpp"
#include "MSTL/core/algorithm/ext_sort.hpp"
#include "MSTL/core/async/async.hpp"
#include "MSTL/core/async/barrier.hpp"
#include "MSTL/core/async/latch.hpp"
#include "MSTL/core/async/scoped_thread.hpp"
#include "MSTL/core/async/thread_pool.hpp"
#include "MSTL/core/async/virtual_thread.hpp"
#include "MSTL/core/async/timer.hpp"
#include "MSTL/core/container/bitmap.hpp"
#include "MSTL/core/container/bitset.hpp"
#include "MSTL/core/container/list.hpp"
#include "MSTL/core/container/lock_free_queue.hpp"
#include "MSTL/core/container/map.hpp"
#include "MSTL/core/container/multimap.hpp"
#include "MSTL/core/container/multiset.hpp"
#include "MSTL/core/container/set.hpp"
#include "MSTL/core/container/unordered_map.hpp"
#include "MSTL/core/container/unordered_multimap.hpp"
#include "MSTL/core/container/unordered_multiset.hpp"
#include "MSTL/core/container/unordered_set.hpp"
#include "MSTL/core/encrypt/encrypt.hpp"
#include "MSTL/core/file/env/env_builder.hpp"
#include "MSTL/core/file/env/env_parser.hpp"
#include "MSTL/core/file/file_watcher.hpp"
#include "MSTL/core/file/ini/ini_builder.hpp"
#include "MSTL/core/file/ini/ini_parser.hpp"
#include "MSTL/core/file/json/json_builder.hpp"
#include "MSTL/core/file/json/json_parser.hpp"
#include "MSTL/core/file/temp_file.hpp"
#include "MSTL/core/file/toml/toml_builder.hpp"
#include "MSTL/core/file/toml/toml_parser.hpp"
#include "MSTL/core/file/yaml/yaml_builder.hpp"
#include "MSTL/core/file/yaml/yaml_parser.hpp"
#include "MSTL/core/functional/bind.hpp"
#include "MSTL/core/iterator/insert_iterator.hpp"
#include "MSTL/core/iterator/ranges.hpp"
#include "MSTL/core/memory/trace_memory.hpp"
#include "MSTL/core/string/vsprintf.hpp"
#include "MSTL/core/system/cmdline.hpp"
#include "MSTL/core/system/console.hpp"
#include "MSTL/core/system/device/serial_port.hpp"
#include "MSTL/core/system/device/storage_device.hpp"
#include "MSTL/core/system/process.hpp"
#include "MSTL/core/system/signal.hpp"
#include "MSTL/core/system/sysinfo.hpp"
#include "MSTL/core/system/environment.hpp"
#include "MSTL/core/time/click.hpp"
#include "MSTL/core/typeinfo/check_type.hpp"
#include "MSTL/core/utility/any.hpp"
#include "MSTL/core/utility/expected.hpp"
#include "MSTL/core/utility/variant.hpp"
#include "MSTL/database/database_pool.hpp"
#include "MSTL/database/mysql/mysql_connect.hpp"
#include "MSTL/database/postgresql/postgresql_connect.hpp"
#include "MSTL/database/redis/redis_connect.hpp"
#include "MSTL/database/redis/redis_result.hpp"
#include "MSTL/database/sql_builder.hpp"
#include "MSTL/database/sqlite/sqlite_connect.hpp"
#include "MSTL/logging/file_sink.hpp"
#include "MSTL/logging/logger.hpp"
#include "MSTL/network/http/http_client.hpp"
#include "MSTL/network/http/http_server.hpp"
#include "MSTL/network/http/http_server.hpp"
#include "MSTL/plugin/plugin_manager.hpp"
#endif // MSTL_MSTL_HPP__
