#ifndef NEFORCE_CORE_SERIALIZE_BINARY_SERIALIZER_HPP__
#define NEFORCE_CORE_SERIALIZE_BINARY_SERIALIZER_HPP__
#include "NeForce/core/memory/endian.hpp"
NEFORCE_BEGIN_NAMESPACE__

// TODO: 实现 binary_serializer 结构

NEFORCE_END_NAMESPACE__
#endif // NEFORCE_CORE_SERIALIZE_BINARY_SERIALIZER_HPP__
