#ifndef NEFORCE_CORE_SERIALIZE_JSON_SERIALIZER_HPP__
#define NEFORCE_CORE_SERIALIZE_JSON_SERIALIZER_HPP__
#include "NeForce/core/file/json/json_builder.hpp"
#include "NeForce/core/reflect/reflect.hpp"
NEFORCE_BEGIN_NAMESPACE__

NEFORCE_END_NAMESPACE__
#endif // NEFORCE_CORE_SERIALIZE_JSON_SERIALIZER_HPP__
