#
# Cross-compilation toolchain for ARM64 (AARCH64) on Windows X64 host
#
set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR ARM64)

if(DEFINED ENV{VCToolsInstallDir})
    cmake_path(SET _vctools "$ENV{VCToolsInstallDir}")
else()
    foreach(_vs_base IN ITEMS
        "D:/Microsoft Visual Studio/2022/Community"
        "C:/Program Files/Microsoft Visual Studio/2022/Enterprise"
        "C:/Program Files/Microsoft Visual Studio/2022/Community")
        if(EXISTS "${_vs_base}/VC/Auxiliary/Build/vcvarsall.bat")
            file(GLOB _msvc_dirs "${_vs_base}/VC/Tools/MSVC/*")
            if(_msvc_dirs)
                list(GET _msvc_dirs 0 _vctools)
                break()
            endif()
        endif()
    endforeach()
endif()

if(DEFINED _vctools)
    cmake_path(APPEND _cl "${_vctools}" bin Hostx64 arm64 cl.exe)
    set(CMAKE_C_COMPILER   "${_cl}")
    set(CMAKE_CXX_COMPILER "${_cl}")
else()
    message(FATAL_ERROR "Cannot locate MSVC ARM64 cross-compiler. Install ARM64 build tools in Visual Studio.")
endif()

if(DEFINED ENV{WindowsSdkDir} AND DEFINED ENV{WindowsSDKVersion})
    cmake_path(SET _sdkroot "$ENV{WindowsSdkDir}")
    cmake_path(SET _sdkver  "$ENV{WindowsSDKVersion}")
    cmake_path(APPEND _sdktools "${_sdkroot}" bin "${_sdkver}" x64)
    set(CMAKE_RC_COMPILER "${_sdktools}/rc.exe")
    set(CMAKE_MT          "${_sdktools}/mt.exe")
else()
    set(_sdk_root "C:/Program Files (x86)/Windows Kits/10/bin")
    file(GLOB _sdk_versions "${_sdk_root}/*")
    set(_sdk_latest "")
    foreach(_v ${_sdk_versions})
        if(IS_DIRECTORY "${_v}")
            get_filename_component(_name "${_v}" NAME)
            if(_name MATCHES "^10\\.0\\.")
                if(NOT _sdk_latest OR _name VERSION_GREATER _sdk_latest)
                    cmake_path(SET _sdk_latest "${_name}")
                endif()
            endif()
        endif()
    endforeach()
    if(_sdk_latest)
        cmake_path(APPEND _sdktools "${_sdk_root}" "${_sdk_latest}" x64)
        set(CMAKE_RC_COMPILER "${_sdktools}/rc.exe")
        set(CMAKE_MT          "${_sdktools}/mt.exe")
    endif()
endif()

if(NOT EXISTS "${CMAKE_RC_COMPILER}")
    message(FATAL_ERROR "Cannot locate Windows SDK rc.exe. Install Windows 11 SDK in Visual Studio.")
endif()
