#include <MSTL/web/http_constants.hpp>
MSTL_BEGIN_NAMESPACE__

#ifdef DELETE
#undef DELETE
#endif

const HTTP_CONTENT HTTP_CONTENT::HTML_TEXT{"text/html"};
const HTTP_CONTENT HTTP_CONTENT::XML_TEXT{"text/xml"};
const HTTP_CONTENT HTTP_CONTENT::CSS_TEXT{"text/css"};
const HTTP_CONTENT HTTP_CONTENT::PLAIN_TEXT{"text/plain"};
const HTTP_CONTENT HTTP_CONTENT::JSON_APP{"application/json"};
const HTTP_CONTENT HTTP_CONTENT::FORM_APP{"application/x-www-form-urlencoded"};
const HTTP_CONTENT HTTP_CONTENT::JPEG_IMG{"image/jpeg"};
const HTTP_CONTENT HTTP_CONTENT::PNG_IMG{"image/png"};
const HTTP_CONTENT HTTP_CONTENT::BMP_IMG{"image/bmp"};
const HTTP_CONTENT HTTP_CONTENT::WEBP_IMG{"image/webp"};
const HTTP_CONTENT HTTP_CONTENT::HTML_MSG{"message/http"};

const HTTP_METHOD HTTP_METHOD::GET{"GET"};
const HTTP_METHOD HTTP_METHOD::POST{"POST"};
const HTTP_METHOD HTTP_METHOD::HEAD{"HEAD"};
const HTTP_METHOD HTTP_METHOD::PUT{"PUT"};
const HTTP_METHOD HTTP_METHOD::DELETE{"DELETE"};
const HTTP_METHOD HTTP_METHOD::OPTIONS{"OPTIONS"};
const HTTP_METHOD HTTP_METHOD::TRACE{"TRACE"};
const HTTP_METHOD HTTP_METHOD::CONNECT{"CONNECT"};
const HTTP_METHOD HTTP_METHOD::DEFAULT = GET & POST & DELETE & PUT & OPTIONS;

const HTTP_COOKIE_NAME HTTP_COOKIE_NAME::JSESSIONID{"JSESSIONID"};
const HTTP_COOKIE_NAME HTTP_COOKIE_NAME::SESSIONID{"SESSIONID"};
const HTTP_COOKIE_NAME HTTP_COOKIE_NAME::PHPSESSID{"PHPSESSID"};
const HTTP_COOKIE_NAME HTTP_COOKIE_NAME::ASPSESSIONID{"ASP.NET_SessionId"};

MSTL_END_NAMESPACE__
