#include "install_consumer.hpp"
#include <NeForce/core/memory/memory_pool.hpp>
#include <NeForce/core/reflect/reflect.hpp>
#include <NeForce/core/system/console.hpp>

#if !defined(NEXUSFORCE_VERSION) || !defined(NEXUSFORCE_VERSION_MAJOR) || !defined(NEFORCE_SUPPORT_OPENSSL) || \
        !defined(NEFORCE_SUPPORT_PCRE2) || !defined(NEFORCE_SUPPORT_ICU)
#    error "the installed NexusForce package did not propagate its interface compile definitions"
#endif

using namespace neforce;
using namespace neforce::reflect;

namespace {
    uint32_t checks = 0;
    uint32_t failures = 0;

    void check(const bool passed, const string& what) {
        ++checks;

        if (passed) {
            println(string("[ OK ] ") + what);
        } else {
            ++failures;
            println(string("[FAIL] ") + what);
        }
    }

    bool registered(const char* name) { return registry::instance().find(name) != nullptr; }
} // namespace

int main() {
    println(string("NexusForce install consumer, headers ") + NEXUSFORCE_VERSION + ", package " +
            NEXUSFORCE_EXPECTED_VERSION);

    check(string(NEXUSFORCE_VERSION) == string(NEXUSFORCE_EXPECTED_VERSION),
          "headers agree with the version the package reports");

    // --- code generated by NFRS for this project's own headers ---------------------------------
    auto* color = registry::instance().find("InstallConsumerColor");
    check(color != nullptr && color->is_enum(), "NFRS registered the enum declared in this project");

    if (color != nullptr && color->enum_info() != nullptr) {
        int64_t blue = 0;
        check(color->enum_info()->value_of("Blue", blue) && blue == 2,
              "enum entry lookup by name through the registry");
    }

    auto* order = registry::instance().find("InstallConsumerOrder");
    check(order != nullptr, "NFRS registered the object type declared in this project");

    if (order != nullptr) {
        check(order->size() > 0, "registered type reports its size");
        check(order->get_property("id") != nullptr && order->get_property("name") != nullptr &&
                      order->get_property("amount") != nullptr,
              "every declared property is registered");

        auto* amount = order->get_property("amount");
        check(amount != nullptr && amount->is_optional(), "property attributes survive code generation");

        auto instance = order->create();
        check(instance.has_value() && instance.raw() != nullptr, "a reflected type can be constructed");

        if (instance.has_value()) {
            auto* prop_id = order->get_property("id");
            auto* prop_name = order->get_property("name");

            if (prop_id != nullptr) {
                prop_id->set(instance.raw(), meta_any(7));
                check(prop_id->get(instance.raw()).get<int>() == 7, "property set/get round trip");
            }

            if (prop_name != nullptr) {
                prop_name->set(instance.raw(), meta_any(string("nexus")));
                auto read_back = prop_name->get(instance.raw());
                check(read_back.has_value() && read_back.get<string>() == "nexus", "string property round trip");
            }
        }
    }

    // --- reflected functions -------------------------------------------------------------------
    auto* worker_meta = registry::instance().find("InstallConsumerWorker");
    check(worker_meta != nullptr, "NFRS registered the type holding member functions");

    InstallConsumerWorker worker;
    worker.count = 10;

    if (worker_meta != nullptr) {
        auto* reset = worker_meta->get_function("reset");
        if (reset != nullptr) {
            reset->invoke(&worker);
            check(worker.count == 0, "reflected member function invoked on a live object");
        }

        auto* compute = worker_meta->get_function("compute");
        if (compute != nullptr) {
            vector<meta_any> args;
            args.emplace_back(3);
            args.emplace_back(4);

            auto result = compute->invoke(&worker, args);
            check(result.has_value() && result.get<int>() == 7, "reflected function returns its result");
        }
    }

    // --- inheritance ---------------------------------------------------------------------------
    auto* derived = registry::instance().find("InstallConsumerDerived");
    if (derived != nullptr) {
        check(derived->is_derived_from("InstallConsumerBase"), "base relation recorded in the registry");
        check(derived->all_properties().size() >= 2, "inherited properties are visible on the derived type");
        check(derived->get_property("base_field") != nullptr, "a base property resolves through the derived type");
    }

    // --- signals -------------------------------------------------------------------------------
    auto* emitter_meta = registry::instance().find("InstallConsumerEmitter");
    InstallConsumerEmitter emitter;
    signal_base* base = &emitter.onChanged;

    check(base->slot_count() == 0, "a freshly constructed signal has no slots");

    if (emitter_meta != nullptr) {
        bool declared = false;
        for (const auto& name: emitter_meta->signal_names()) {
            if (name == "onChanged") {
                declared = true;
                break;
            }
        }
        check(declared, "signal declared in this project is registered");
    }

    InstallConsumerWorker receiver;
    if (worker_meta != nullptr) {
        auto* slot = worker_meta->get_function("setCount");
        if (slot != nullptr) {
            check(registry::connect_signal_to_slot(base, slot, &receiver), "signal connected to a reflected function");

            emitter.onChanged.emit(5);
            check(receiver.count == 5, "signal emission reaches the reflected receiver");
        }
    }

    // --- the library itself, beyond reflection --------------------------------------------------
    string text = "NexusForce";
    text += " install";
    check(text == "NexusForce install", "core string facilities work from an installed package");
    check(registered("InstallConsumerOrder"), "registry lookup is stable across repeated queries");

    // --- the allocator model --------------------------------------------------------------------
    memory_pool& pool = system_memory_pool();
#ifdef NEFORCE_USING_MEMORY_POOL
    string pooled(96, 'x');
    check(pool.owns(pooled.data()), "the installed package routes library containers to the memory pool");
#endif
    check(pool.foreign_release_count() == 0, "no allocation crossed the allocator boundary");

    println(string("checks: ") + to_string(checks) + ", failures: " + to_string(failures));

    if (failures != 0) {
        println("INSTALL CONSUMER FAILED");
        return 1;
    }

    println("INSTALL CONSUMER PASSED");
    return 0;
}
