name: "GTest Coverage"

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get install -y cmake build-essential ninja-build libtirpc-dev libc++abi-dev
          pip install gcovr

      - name: Compile and Run
        run: |
          mkdir build && cd build
          cmake .. -G "Ninja" -DCMAKE_BUILD_TYPE=Debug -DNEXUSFORCE_BUILD_COVERAGE=ON
          ninja
          ./bin/NexusForceUnitTests

      - name: Generate Coverage Report
        run: |
          cd build
          gcovr -r .. --xml -o coverage.xml \
            --exclude '/usr/.*' \
            --exclude '/opt/.*' \
            --exclude 'build/.*' \
            --exclude 'vcpkg/.*' \
            --exclude 'vcpkg_installed/.*' \
            --exclude '_deps/.*' \
            --exclude 'third_party/.*
            --exclude 'tests/.*

      - name: Update via Codecov
        uses: codecov/codecov-action@v4
        with:
          files: build/coverage.xml
          flags: unittests-linux
